### ISSUE TITLE
PhCalibration analysis with MoReWeb for variable Vcal steps

### ISSUE THREAD

**Issue by thweiler** [psi46/MoReWeb#104]
Is it possible to analyse PhCalibration files from the actual pXar version which uses 
a variable steps size in the gainPedestalTest?

cheers
Thomas

**Comment by piberger** [comment]
Hi Thomas,

this should be possible now with the latest commit.
The number of points in now flexible and taken from the .dat file and points with PH=0 are ignored for the fit.

cheers,
Pirmin

**Comment by thweiler** [comment]
Hello Pirmin
After the git pull I get following errors.
(on SL6 and OSX)
cheers
Thomas

MORE web analysis script, Revision number 1
GlobalFinalResultsPath: "/Users/weiler/psiexpert/MoReWeb/DATA/FinalResults/REV001"
AnalyseTestData ['M4521', 'Fulltest', '2015-06-24', '09h04m26s', '1435129466'] M4521_Fulltest_2015-06-24_09h04m26s_1435129466
['M4521', 'Fulltest', '2015-06-24', '09h04m26s', '1435129466'] M4521_Fulltest_2015-06-24_09h04m26s_1435129466
check whether module M4521 with QualificationType Fulltest exists in DB: 
Extract Tests from config file
analyse_test_list
	-> appendFulltest
done with extraction
/Users/weiler/psiexpert/MoReWeb/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Fulltest.py:274: SyntaxWarning: import * only allowed at module level
  def CustomWriteToDatabase(self, ParentID):
/Users/weiler/psiexpert/MoReWeb/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Fulltest.py:274: SyntaxWarning: import * only allowed at module level
  def CustomWriteToDatabase(self, ParentID):
Traceback (most recent call last):
  File "./Controller.py", line 335, in <module>
    AnalyseAllTestDataInDirectory(GlobalDataDirectory)
  File "./Controller.py", line 265, in AnalyseAllTestDataInDirectory
    AnalyseTestData(ModuleInformationRaw,Folder)
  File "./Controller.py", line 218, in AnalyseTestData
    ModuleTestResult = GetModuleTestResult(TestResultEnvironment,FinalModuleResultsPath,ModuleInformation)
  File "./Controller.py", line 183, in GetModuleTestResult
    InitialAttributes = newModuleInformation
  File "/Users/weiler/psiexpert/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 270, in __init__
    i['DisplayOptions']
  File "/Users/weiler/psiexpert/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 270, in __init__
    i['DisplayOptions']
  File "/Users/weiler/psiexpert/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 270, in __init__
    i['DisplayOptions']
  File "/Users/weiler/psiexpert/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 259, in __init__
    f = __import__(importdir + '.TestResult', fromlist=[''])
  File "/usr/local/root/lib/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
ImportError: No module named DacDac.TestResult

**Comment by piberger** [comment]
I accidentally committed another change without adding all of the files, try again please.

**Comment by thweiler** [comment]
Thanks, now it was running on an old phCalibration file and a new one.
cheers
Thomas

**Comment by piberger** [comment]
Hi, thanks for testing and reporting, I'll close it.
