### ISSUE TITLE
QualificationGroup.py 'cycle'/'powercycle'

### ISSUE THREAD

**Issue by gfunk723** [psi46/MoReWeb#105]
The string 'cycle' (line 148) is also in 'powercycle' (line 165), so if powercycle comes first in the lists in the .ini file, it will call appendTemperatureCycle for the wrong test. 

The "elif 'powercycle'..." line just needs to be before the "elif 'cycle'..." line.

**Comment by veloxid** [comment]
Hi
You're right.
Fixed with commit 
Cheers
Felix
