### ISSUE TITLE
fullQualification without dead pixels

### ISSUE THREAD

**Issue by rslu** [psi46/MoReWeb#109]
A question regards the analysis if there is dead pixels.
In my opinion the dead pixels should not be used for any other test because the response
create entries away from bulk distribution thus create wrong/overblown "width" measurement such as Vcal threshold width or Gain Width.
The dead pixels have been counted and should not double count in other test.
Do I understand correct, it is the case now?
Can MoreWeb exclude dead pixels for all analysis?

Rong-Shyang

**Comment by piberger** [comment]
Hi Rong-Shyang,
I agree with you, dead pixels should be excluded from other pixel defects. Indeed in some tests dead pixels are double counted at the moment.

Situation right now:
Mask & address: already excluded by pxar, explicit exclusion by MoReWeb
Bump: dead pixels are on left side of peak and therefore implicitly not counted as BB defect (but also explicitly not excluded by MoReWeb)
Trimbit: explicitly excluded by MoReWeb
Threshold problems + width, Gain etc.: not excluded by MoReWeb

This will be fixed.

**Comment by piberger** [comment]
The newest commit ddb03cd should address the issues with dead pixels being double-counted or blowing up RMS.

**Comment by alphatsai** [comment]
Hi all,

We update the MoReWeb and check again the grade B module again, which has dead pixel[1] and was took them to analyze before[2], the new results is shown in grade A[3]. It mean the dead pixel has been excluded during the analysis in current version of MoReWeb.

Many thanks,
Jui-Fa

[1]
![deadpixelontop](https://cloud.githubusercontent.com/assets/6000932/9275532/fec5a77c-429d-11e5-922e-1b03b115f701.png)

[2] Before the update
![beforeupdate](https://cloud.githubusercontent.com/assets/6000932/9275534/fee3c54a-429d-11e5-9e01-9e5706cda616.png)

[3] After the update
![afterupdate](https://cloud.githubusercontent.com/assets/6000932/9275533/fee2c9ec-429d-11e5-8078-9261fb2cebab.png)

**Comment by piberger** [comment]
It seems to work now, therefore I close this issue.
(Blow-up of RMS because of REAL threshold-defects will be addressed soon.)
