### ISSUE TITLE
Empty DC efficiency distribution in specific chip

### ISSUE THREAD

**Issue by ywkao** [psi46/MoReWeb#117]
Hi,

When examining the analysis results of high-rate tests, I found that some modules look fine in every aspect except that on one of the chips, the content of the DC efficiency distribution plot is empty. And strangely, this happens on chip7 in most of cases. For example, below shows the plots of M3046 Chip7:

#Efficiency Interpolation: C7
![efficiencyinterpolation](https://cloud.githubusercontent.com/assets/11542148/10306664/2cf0f08e-6c5b-11e5-8fc2-c7ce326a4ae4.png)
#DC Efficiency Distribution: C7
![doublecolumnefficiencydistribution](https://cloud.githubusercontent.com/assets/11542148/10306691/61612c44-6c5b-11e5-9c27-1a001f779e2b.png)
These results can be found on DB. I cannot figure out why the efficiency interpolation looks fine but the other shows nothing. Is there any possible reason?

Thanks,
Yu-Wei

**Comment by piberger** [comment]
Hi,

I guess for C7 there are not enough data points in the fit range if you look at single double columns. It looks like there is only one single point in this example here. Adding one more rate between the first two, which would be around 65 MHz/cm2 for this chip, would probably help.
For the "#Efficiency Interpolation:" plot which takes into account all double columns there are still enough points and for other ROCs the rates are a bit lower so the third rate moves into the fit range.

The "#DC Efficiency Distribution" plot is not used for grading in any way, so this should not cause any problems.

Pirmin

**Comment by ywkao** [comment]
I have tried taking the data between the first two. And yes, as you said, the result did improve!
Thanks a lot!!
