### ISSUE TITLE
Fit Failed & Grading Questions

### ISSUE THREAD

**Issue by ywkao** [psi46/MoReWeb#118]
Hi,

I discover that one of the chips on M3009 has a failed fit on "efficiency interpolation plot"[1]. As the distribution of the data points looks fine. There is an inefficient double columns on the chip. Would this be the cause of the failed fit?

The other question is, for the same chip, I see the grade of the efficiency@50MHz/cm2 is B. I am wondering why the final grade of the whole module is A.

Thanks,
Yu-Wei

[1] http://cmspixelprod.pi.infn.it/data/pixelslocal/OUT/GLOBAL/M3009/prod-HR-17Sept15a-refit/REV001/R001/M3009_XRayHRQualification_2015-10-05_15h20m_1444051253/QualificationGroup/XRayHRQualification/Chips/Chip1/TestResult.html#d

**Comment by piberger** [comment]
Hi,

I also guess that's why the fit failed, we probably need some chi2/ndf printed here to detect such kind of fit failures. I will look at this tomorrow.

the 50 MHz efficiency is not taken into account in the grading. (All "grades" in ()-brackets are not used)

**Comment by piberger** [comment]
![bad_col_unif](https://cloud.githubusercontent.com/assets/10864232/10399607/f46817dc-6eb3-11e5-900f-6d0b7ed4f549.png)
M3009 C1

Maybe we should tighten the criteria for the column uniformity ratio test a bit, I will collect a bit of statistics and see if we can increase the lower bound, which is 80% right now, to a higher value which would detect this case. We also have one module with a bad double column, which was in a 2nd test just slightly above the 80% (but still visually different from other double columns).

**Comment by piberger** [comment]
In the next version this double column defect is recognized:
![m3009_table_new](https://cloud.githubusercontent.com/assets/10864232/11186886/36c7a49c-8c84-11e5-99f8-f4253a947960.png)
and this double column is then excluded from the fit to prevent a failed fit:
![m3009_fit_new](https://cloud.githubusercontent.com/assets/10864232/11186881/340cebcc-8c84-11e5-87c0-d47014ec8cd0.png)

You can test the changes in the development branch here:
https://github.com/psi46/MoReWeb/tree/dev-v0.6.8

**Comment by ywkao** [comment]
Yes, I have gotten the same result! Thanks a lot!
