### ISSUE TITLE
Updated example input

### ISSUE THREAD

**Issue by lantone** [psi46/MoReWeb#119]
Hi,

We here in FPix-land have started looking into using MoReWeb for visualization (if not grading).  We have a more or less working configuration for "fullTest" type results, but not yet for X-ray results.  Would it be possible to update the example zip files here?:

https://github.com/psi46/MoReWeb/tree/master/examples

Thanks,
Jamie (for the FPix crew)

**Comment by piberger** [comment]
Hi Jamie,

Of course, these examples were quite old...
I updated the X-ray example  XRayQualification_example.tar, which contains high rate tests as well as vcal calibration. Both qualifications can be placed in one folder (like in this example) or in separate folder for VcalCalibration and HR.
Fulltest example will be updated soon including the new setvana test output from pxar.

cheers,
Pirmin

**Comment by lantone** [comment]
That's great, thanks Pirmin.  While I have your attention, one more thing: Where can I find the central MoReWeb database for BPix?  The MoReWeb twiki points me here: http://cmspixel.pi.infn.it/cgi-bin/ModuleQualificationOverview.cgi, but there don't seem to be any recent results.  

Thanks,
Jamie

**Comment by piberger** [comment]
new database is here:
http://cmspixelprod.pi.infn.it/
