### ISSUE TITLE
The Column Read Unif. problem

### ISSUE THREAD

**Issue by ywkao** [psi46/MoReWeb#148]
Dear experts,

Today, we tested a module, M3262, which is reported as grade C due to `the Column Read. Unif. at low rate (~50 MHz/cm2)' on chip 4. However, we are unable to recognize the problem from analysis plots, and there is no any error message during the HR tests.
Could someone help clarify the reason?

Thanks,
Yu-Wei

DB: http://cmspixelprod.pi.infn.it/data/pixelslocal/OUT/GLOBAL/M3262/prod-MW1.0.1/REV001/R001/M3262_XRayHRQualification_2016-06-14_11h14m_1465895696/QualificationGroup/XRayHRQualification/TestResult.html#d

**Comment by piberger** [comment]
Hi Yu-Wei,

in column 32, between from event 4320000 to 4330000 (bin 432), number of hits was 379, which is 11.1 sigma away from mean 215 and max 10 sigma are allowed.

It happened also few more times that the number was too high, but still below 10 sigma, but only in column 32. I guess a single pixel is responsible for this, which becomes a hot pixel occasionally. We have seen this once, but it was a lot more obvious, here its very close to the threshold.

One could try yo run the retrim hot pixels test with longer data taking time and stricter thresholds, or increase vthrcomp a bit to increase the probability of this pixel becoming a hot pixel, run retrim hot pixels and then go back to original vthrcomp value.
Or find out which pixel it is (use "filltree" option in pxar to get full data) and mask it.

Hits in column 32:

![m3262_hits](https://cloud.githubusercontent.com/assets/10864232/16116861/7ab25e84-33cf-11e6-8576-86abfd2f2cf2.png)

````
found non-uniform readout in bin  432 (of 987)  in Column  32
 -> mean #hits = 215.774291498
 -> #hits = 379.0
 -> sigma = 14.6892576905
 -> n sigma =  11.1119099373
````

**Comment by ywkao** [comment]
Hi Pirmin,

Thanks for your elucidation! The problem has been solved and M3262 is grade A now.
I tried the method of tuning vthrcomp value. It turns out that there is a pixel being retrimed to higher trim bit, and one pixel being masked out.

Thank you,
Yu-Wei
