### ISSUE TITLE
Initial Current

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#18]
Readout initial current and add it to overview page

**Comment by veloxid** [comment]
What is the status Vittorio?

**Comment by veloxid** [comment]
Afaik this feature has been implemented,
@vtavolar: Could you please tell us what is the name of the plot?
We should include it in each QualificationGroup if data is taken with Pxar...

**Comment by vtavolar** [comment]
the plots stored in the pxar rootfile are named HD for digital current and HA for analog one

**Comment by veloxid** [comment]
Implemented
