### ISSUE TITLE
Directory structure of revisions

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#29]
At the moment revision number is doubled:
instead of 
GlobalFinalResultsPath/REV001/R001/MCERN...
this:
GlobalFinalResultsPath/REV001/MCERN...

If no GlobalFinalResultsPath exists than extend FinalResults by -R001:
e.g.
MCERN,.........23902390329023/FinalResults-REV001/

**Comment by veloxid** [comment]
Wie siehts aus?

**Comment by macjohnny** [comment]
sorry, ging vergessen.
gibts in nächster zeit sonst noch was zu tun? dann würde ich es bündeln.

**Comment by veloxid** [comment]
Irgendwann noch einige Aufgaben bzgl. Xray. Da muessen wir aber auf Martin Limpinski warten, daher eher nein...
Eventuell kannst du dir auch Issue #28 annehmen.
