### ISSUE TITLE
Xray-Vthrcomp Method error

### ISSUE THREAD

**Issue by misalvat** [psi46/MoReWeb#38]
Hi,

I got tthe following error during the analysis of R0215_VcalCalibration folder (in the examples):

ErrorList:
{'ErrorCode': KeyError('Target',), 'FinalResultsStoragePath': '/home/michelecms/DTB/MoreWeb/Analyse/DATA/FinalResults/REV001/R001/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/QualificationGroup/XrayCalibrationSCurve_1/VcalCalibrationModule/VcalCalibration_SCurve_ROC0', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationModule.VcalCalibrationROC'}
	 - TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationModule.VcalCalibrationROC: 'Target'
{'ErrorCode': KeyError('Slope',), 'FinalResultsStoragePath': '/home/michelecms/DTB/MoreWeb/Analyse/DATA/FinalResults/REV001/R001/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/QualificationGroup/XrayCalibrationSCurve_1/VcalCalibrationModule', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationModule'}
	 - TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationModule: 'Slope'
{'ErrorCode': KeyError('Slope',), 'FinalResultsStoragePath': '/home/michelecms/DTB/MoreWeb/Analyse/DATA/FinalResults/REV001/R001/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/QualificationGroup/XrayCalibrationSCurve_1/VcalCalibrationSlope_SCurve', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationSlope'}
	 - TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationSlope: 'Slope'
{'ErrorCode': KeyError('Offset',), 'FinalResultsStoragePath': '/home/michelecms/DTB/MoreWeb/Analyse/DATA/FinalResults/REV001/R001/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/QualificationGroup/XrayCalibrationSCurve_1/VcalCalibrationOffset_SCurve', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationOffset'}
	 - TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationOffset: 'Offset'
{'ErrorCode': KeyError('chi2',), 'FinalResultsStoragePath': '/home/michelecms/DTB/MoreWeb/Analyse/DATA/FinalResults/REV001/R001/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/QualificationGroup/XrayCalibrationSCurve_1/VcalCalibrationChi2_SCurve', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationChi2'}
	 - TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.VcalCalibrationChi2: 'chi2'
{'ErrorCode': AttributeError("'NoneType' object has no attribute 'Clone'",), 'FinalResultsStoragePath': '/home/michelecms/DTB/MoreWeb/Analyse/DATA/FinalResults/REV001/R001/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/QualificationGroup/XrayCalibrationSCurve_1/Chips_Xray/Chip_Xray0/Xray_Calibration_SCurve_Chip0', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.Chips_Xray.Chip_Xray.XrayCalibrationChipResults'}
	 - TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration.Chips_Xray.Chip_Xray.XrayCalibrationChipResults: 'NoneType' object has no attribute 'Clone'
michelecms@cleanroom-desktop:~/DTB/MoreWeb/Analyse$ python Controller.py

Approximately this happens  after the commit 91454bca2a626fcecd6c27aa7cb947cf880e6b47...

Thanks
Michele

**Comment by veloxid** [comment]
@misalvat: is the problem solved?
