### ISSUE TITLE
Problem with running MoreWeb

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#39]
Hello!  I am a graduate student working with the HEP group at University of Nebraska - Lincoln and I am trying to get MoReWeb working.  I am able to run a full test using El Comandante and when I try to run the MoReWeb script it appears as if it works but there are no final results in my local DB.  I know that MoReWeb itself is working because I can get results for the test data provided, so I am confused as to what is wrong with my actual data.  It does not generate any errors, so I am not even sure what my first step should be.  I apologize that this is such a vague question, but I am honestly getting no feedback from MoReWeb in terms of something going wrong except that nothing appears in my “Overview.html” file for the module data.  

Please let me know further information I could provide that would be helpful to you.  I know that with the time difference it might be difficult, but next week is finals week so I have no class/teaching and we could possibly set up a time to Skype, if you think that would be more helpful.

Thanks for your time,

Amanda Steck

**Comment by macjohnny** [comment]
@veloxid gibts da was neues?

**Comment by veloxid** [comment]
Seems to be solved...
i close it.
