### ISSUE TITLE
adding more points to the high (or low) range in a gain/pedestal calibration

### ISSUE THREAD

**Issue by ursl** [psi46/MoReWeb#40]
Hi all,

I propose to add the capability to moreweb that it scans the first lines of the files phCalibration_C*.dat

    Pulse heights for the following Vcal values:
    Low range:  50 100 150 200 250 
    High range:  10 17 24 30 50 70 90 120 200 
    
    0   0  27  34  42   0  26  32  34  58  76  98 130 162    Pix  0  0
    0   0  32  35  42   0  26  34  41  58  78  99 136 162    Pix  0  1
    0   0  33  39  44   0  26  34  41  58  78  99 133 162    Pix  0  2
    // etc ...

and understands how many points are written in the low and in the high range. (You'll notice that here the high range got "extended" by points at 17, 24, and 120.)

The reason for my proposal is that this will allow 
(1) better determination of the plateau position (with the point at 120)
(2) better determination of the scale factor between low- and high-range if there are more overlap points (17 and 24). 

Of course one could "freeze" this new format, but I think parsing should not be very difficult. As we have seen some changes in the past between the turn-on of the plateau of different ROC generations, the flexibility should be provided to adapt for different ROCs. 

At the moment pxar has an option to measure/dump "extended" gain/pedestal calibration files, which is disabled by default. 

Many thanks for considering this. 

Cheers,
--U.

**Comment by veloxid** [comment]
Should be implemented now. Please try
