### ISSUE TITLE
MoReWeb output for smaller test sets

### ISSUE THREAD

**Issue by khan62** [psi46/MoReWeb#41]
Hi, I am a student working with Purdue University HEP, and we've been trying to use MoReWeb to analyze and display our pXar data. However, we're only interested in the Pretest, PixelAlive, and BumpBonding tests. Is it possible for MoReWeb to analyze and display an arbitrary set of tests, or does it have to be a designated group (Fulltest, XrayCalibration, etc)? What would be required to write our own Qualification Group? 

Thanks for your help,
Kamal

**Comment by macjohnny** [comment]
hi kamal
it is perfectly possible to use only a subset of the tests implemented in the Fulltest.
please have a look at the BareModuleTest (https://github.com/psi46/MoReWeb/tree/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/BareModuleTest). 
make use of the object-oriented structure to inherit code from e.g. the Fulltest.
to achieve this, create your own Specialtest and for each test you want to copy/adapt, create a test-file with the following content:

    import TestResultClasses.CMSPixel.QualificationGroup.Fulltest.Chips.Chip.PixelMap.PixelMap
    class TestResult(TestResultClasses.CMSPixel.QualificationGroup.Fulltest.Chips.Chip.PixelMap.PixelMap.TestResult):
        def CustomInit(self):
            # Call Overridden CustomInit()
            super(TestResult, self).CustomInit()

            ROOTConfiguration.initialise_ROOT()
            self.Name='CMSPixel_QualificationGroup_BareModuleTest_Chips_Chip_PixelMapNew_TestResult'
            self.NameSingle='PixelMapNew'

        # PopulateResultData is inherited

Note the following line:
    import TestResultClasses.CMSPixel.QualificationGroup.Fulltest.Chips.Chip.PixelMap.PixelMap

also, you need to adapt the Controller.py file. i suggest you have a look at the parts related to the BareModuleTest
does this help you?
cheers

esteban

**Comment by khan62** [comment]
This does help! Thank you.

Kamal
