### ISSUE TITLE
Vcal threshold RMS inconsistency

### ISSUE THREAD

**Issue by vtavolar** [psi46/MoReWeb#42]
Hello,

in the single chip overview, the Vcal Threshold Trimmed plot shows the correct RMS calculation in the stats box, but in the summary just below it a wrong RMS is quoted (because calculated over the full DAC range, I believe) (see attached example). This latter RMS is then also displayed in electrons in the module summary plots. Can this be fixed?

Furthermore, it would be great if in the Vcal Threshold Trimmed plot the number of entries could be somehow updated to the entries really shown in the range (currently 4160 entries are always quoted in the stats box).

Thanks,
Vittorio

![screen shot 2015-02-02 at 13 16 53](https://cloud.githubusercontent.com/assets/5130294/6000598/faeceb70-aadf-11e4-89b3-ff7a3dfb7c90.png)

**Comment by macjohnny** [comment]
hi
i will have a look at it.
but i don't understand what you mean by "it would be great if in the Vcal Threshold Trimmed plot the number of entries could be somehow updated to the entries really shown in the range". can you explain it a bit more?

**Comment by ursl** [comment]
My guess is that you should also display the "integral"

Cheers,
--U.

**Comment by vtavolar** [comment]
Hi,
thanks for your reply. 
About the number of entries, I mean the following:
in the plot the x-axis range is limited to 0-100. In this way, all bins above 100 are not included in RMS calculation displayed in the stats box, providing the correct value. Nevertheless, the number of entries is still 4160. I believe this is a ROOT feature and depends on the binning chosen at the moment of declaration of the TH1 and not on the Range chosen for the axis. 
I would like this number to be updated to the number of entries actually displayed in the range chosen.
Looking at the TH1 documentation, I see two possible solutions:
-use SetBinsinstead of SetRangeUser, but in this way the content of bins outside the range is lost
-display the Integral calculated in the appropriate range

Thanks,
Vittorio

**Comment by piberger** [comment]
@vtavolar 's commit faae7d6 replaced RMS with sigma of fitted Gaussian.
