### ISSUE TITLE
Vcal calibration -> DB Upload

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#43]
In order to make the Upload to the DB of the vcal calibration as easy as possible, 
Please collect the following variables in the XrayCalibration.py in a similar way as done in the Fulltest.py.
Be found at: https://indico.cern.ch/event/360854/contribution/3/material/slides/4.pdf

Content for vcal calibration: 
X-Ray calibration with known energies
 DB name: “XRayVcalCalibration”
On ROC Level
![screen shot 2015-02-03 at 13 51 09](https://cloud.githubusercontent.com/assets/1712549/6020399/da5acf22-abab-11e4-9f96-53fa13c73af5.png)

On Module Level:
![screen shot 2015-02-03 at 13 52 37](https://cloud.githubusercontent.com/assets/1712549/6020418/f8b8328e-abab-11e4-9c06-2a82fc6960e2.png)

**Comment by veloxid** [comment]
Adding the missing items in function CustomWriteToDatabase
especially the one we need on ROC level are not there yet...

similar to line 240 - 257

**Comment by macjohnny** [comment]
hi
i added the functionality for gathering the data in XrayCalibration.py
some questions:
- is there a particular reason why there is a VcalCalibrationROC test for each chip in the VcalCalibrationModule folder and not in the Chips_Xray/Chip_Xray folder?
- who will implement the target hit rates?
- @tommasoboccali can you have a look at the code and see whether it is ok for you like this? i tried to have it similar to the Fulltest.

**Comment by macjohnny** [comment]
Hi Felix,
 
it is hitrate=N_Hits/(N_Triggers*25ns*Area). You can get from the root file N_Hits for every ROC from the histogram Xray.hMap_target_C%i_V0 and N_Triggers from Xray.ntrig_target_V0. For the area you could estimate 52*80*0,1mm*0,15mm= 62,4 mm².
With grading for XRay you mean for the Vcal calibration? We could add two cuts on the slope and two on the offset (if cut_1 < slope < cut_2, ROC is ok, if not it is bad) and a cut on chi²/ndf on the fit. To know if this works I would need more data from other centers, because there can be systematic effects and one center could for example measure always slightly higher values.
 
 
Greetings,
Martin

**Comment by veloxid** [comment]
I would suggest to make r a roc grading with to levels: 
e.g. slope_Upper_B, slope_Upper_C, slope_lower_B, slope_lower_C
cuts on slope, offset, chi2, and option for rates

for the module: grade on worst roc, option for spread cuts, prepatre to add more grading criteria

**Comment by MartinLip** [comment]
I think grading with two levels might be overkill, because basically we jsut want to check if the ROC works or not. But you could implement it, and we could later fall back to a two grade sheme if that is sufficient.

A ROC should not be graded concerning the hit rate in this test, but a warning should be given if the rate is below a given value (100 kHz/cm²).

**Comment by arizzi** [comment]
@tommasoboccali @veloxid @macjohnny we had a look, more  or less the code seem ok (beside  we will need to change the insert function from            pdb.insertTestFullModuleDirPlusMapv96Plus(s.SESSION_ID, Row)
to something new dedicated to xray.

we tried to run it, on the tar file https://twiki.cern.ch/twiki/pub/CMS/BPixX-rayCalibration/EXAMPLEMODULE_XRayVcalCalibration_2015-02-01_12h34m_1422794101.tar.gz
but we get a lot of errors (beside some python syntax errors that we fixed on the fly).... do you have a better file?
Did you guys actually try to run it?

**Comment by macjohnny** [comment]
Ok, so i will implement the grading and then you can have a look at it again. Please merge any changes into this branch, not master, so that we can merge it alltogether to master

**Comment by arizzi** [comment]
we make no changes till it can at least run on some example input file. Do you have a running version? (or a working input file?)

**Comment by veloxid** [comment]
Hi,
Sorry  I only had time to test it this week., I found one typo which made some problems + I solved the issue with  the scurve method (issue #45) , I do not get any errors anymore. 
I also included the hit rate measurement.
You might have to rename the folder from EXAMPLEMODULE_... to MXXXX_...
I tested with the newest version in the master branch: 898995c25f788fd719b3008e3e45d365e302487d
Cheers
Felix

**Comment by veloxid** [comment]
we merged the changes of the maser into the branch  macjohnny-dev-Vcalibration 
I tested it and it seems to work, i do not get any errrors.

**Comment by arizzi** [comment]
a few things we spotted that are not working:
 Key = "VcalCalibration_{Method}_ROC{ROC}".format(Method=self.Attributes['Method'], ROC=roc)

roc is undefined, should be ChipNo?

then:
 self.ResultData['SubTestResults']['VcalCalibrationModule'].ResultData['SubTestResults'][i]

what is "i"?

**Comment by arizzi** [comment]
we guessed
                Key = "VcalCalibration_{Method}_ROC{ROC}".format(Method=self.Attributes['Method'], ROC=ChipNo)

and

                VcalChipTestResultObject = self.ResultData['SubTestResults']['VcalCalibrationModule'].ResultData['SubTestResults']["VcalCalibration_Spectrum_ROC%i"%ChipNo]

**Comment by macjohnny** [comment]
hey
thanks, thats right, it should bie ChipNo
and "i" should be "Key". i will change this.

**Comment by macjohnny** [comment]
i corrected it
is it ok now?

**Comment by veloxid** [comment]
I tried it with commenting the DB stuff, after another typo fix, it seeems to work for me

**Comment by arizzi** [comment]
we more or less impelmented all the calls, will merge with your latest commits in few minutes, but it seems there are still some empty variables... more later..

**Comment by arizzi** [comment]
@macjohnny you should be able to merge 0f2fd6c, do you want a PR ?

**Comment by arizzi** [comment]
there seem to be quite some empty stuff (SLOPE,OFFSET,CHI2 etc...)
https://cmspixelprod.pi.infn.it/cgi-bin/view.cgi?objName=Test_FullModule_XRay_Vcal_Roc_Analysis
