### ISSUE TITLE
Histogram naming problem with X-Ray Vcal calibration,

### ISSUE THREAD

**Issue by MartinLip** [psi46/MoReWeb#44]
Hi,
when you analyse module x-ray data you will not get the results for Chip 1, because of multiple possible histogram candidates:

```
'ErrorCode': NameError('Found more than one possible candidate for the Xray spectrum: [<ROOT.TKey object ("q_Zn_C1_V0") at 0x10ff28a0>, <ROOT.TKey object ("q_Zn_C10_V0") at 0x10ff35c0>, <ROOT.TKey object ("q_Zn_C11_V0") at 0x10ff3740>, <ROOT.TKey object ("q_Zn_C12_V0") at 0x10ff38c0>, <ROOT.TKey object ("q_Zn_C13_V0") at 0x10ff3a40>, <ROOT.TKey object ("q_Zn_C14_V0") at 0x10ff3bc0>, <ROOT.TKey object ("q_Zn_C15_V0") at 0x10ff3ce0>]',), [...]
```
Multiple candidates for Chip 1 are 10,11,12,13,14,15, other chips have an unambigious name, thus only chip 1 data is missing, all others are fine.
The Problem is caused in moreweb/Analyse/AbstractClasses/Helper/HistoGetter.py.

My current workaround is just to remove the check for more than possible candidate, but that is maybe not safe?

**Comment by veloxid** [comment]
Please try fix with from revision: #eb145e
Should fix this, checking now for 'C{ROC}_' instead of 'C{ROC}' this should solve the issue.
