### ISSUE TITLE
Vcal Calibration: Separation of Spectrum and Threshold Method

### ISSUE THREAD

**Issue by MartinLip** [psi46/MoReWeb#45]
For the production we will only use the spectrum method for vcal calibration.
Currently moreweb throws out lots of errors when only the spectrum method is present in the root file, because it is also expecting the threshold method to be there. Is it possible to tell moreweb (e.g. via elCommandante.ini) that there is only one method in the file, so we don't get these errors?

**Comment by veloxid** [comment]
Please provide a sample than we can test it.

**Comment by MartinLip** [comment]
Hi Felix,

you can find an example here:
https://twiki.cern.ch/twiki/pub/CMS/BPixX-rayCalibration/EXAMPLEMODULE_XRayVcalCalibration_2015-02-01_12h34m_1422794101.tar.gz

**Comment by veloxid** [comment]
It would be great if the detection can be done automatically...
and just does not produce errors if only one of the kind is there...

**Comment by macjohnny** [comment]
@veloxid unfortunately, i cannot access the file due to a permission problem.

**Comment by veloxid** [comment]
I send you in private another Link look at your Mails

**Comment by veloxid** [comment]
should be solved now,
