### ISSUE TITLE
Fix software detection or add overwrite flag

### ISSUE THREAD

**Issue by piberger** [psi46/MoReWeb#46]
Hi,

the automatic software detection in GeneralTestResult.py:check_Test_Software does not reliably when pxar and elComandante are used and defaults to "psi46expert".
Please fix this or add a parameter to the config file to override software detection.

**Comment by veloxid** [comment]
It seems that there is no file anymore which is called *pxar*.*, this was the way how it was detected in the past, maybe @ursl can  comment on that. Is there no file more where we can detect that it is  pxar and not another software?
If there would be an empty pxar.log file or something like that in the default parameters it should work

**Comment by ursl** [comment]
Hi Felix,

I am not sure what you mean. In principle there is always a pxar.log and a
pxar.root file in the directory where pXar dumps its output. Now, if you
run multiple tests into the same directory, then you can *in addition* have
other time-stamped output files with the same "base name". But the most
recent files should always simply have the bare names pxar.{root|log}.

Cheers,
--U.

**Comment by veloxid** [comment]
if one runs it with elComandante the naming of the root file is set by the pxar arg option:
-r %(rootfilename)s.root'
it seems that the log will be name %(rootfilename)s.log
Than no file is there which is named pxar.log

**Comment by ursl** [comment]
well, yes, if you on purpose change the filename then pxar will comply
and put out a matching logfile. I think that the logfile name should
match the roofile name. But then (I guess) your
GeneralTestResult.py:check_Test_Software should check for
%(rootfilename)s.log? I must still be missing something...

Cheers,
--U.

**Comment by veloxid** [comment]
yes there is a logfile called %(rootfilename)s.log, but I am looking for a file on which i can recognize pxar 100%.
If the naming of the root and log file can be set arbitrary this are not really the right candidates...

**Comment by ursl** [comment]
Hi Felix, 

can you try https://github.com/psi46/pxar/commit/dd190fbf37251bf6561d962bda21f0192ec5a8e5? This should dump the line 

[08:56:30.486]     INFO: *** Welcome to pxar ***

as first line into the XXX.log file (whatever XXX is). I think you'll have to grep for "Welcome to pxar", because pxarCore also puts "pxar" into the logfile, but that might be present when pxarCore is used from other programs. 

Cheers,
--U.

**Comment by piberger** [comment]
If it doesn't find a file called pxar.log, it checks all log files for the "Welcome to pxar" in the first line now.
