### ISSUE TITLE
Grading algorithm 

### ISSUE THREAD

**Issue by alphatsai** [psi46/MoReWeb#47]
Hi,

We got the results from a full module with different TBM parameters.
Both of results gave different grades from MoReWeb.
I have check the code, if I am not wrong, it seems to find the number of bed ROCs in the full module.
But can you explain how to decide the bed ROC, please?
If it's depend on the bed trim bits number?   

Many thanks,
Jui-Fa

**Comment by macjohnny** [comment]
Hi Jui-Fa
the grading depends on the results of the following subtests:
'Noise', 'VcalThresholdWidth', 'RelativeGainWidth', 'PedestalSpread', 'Parameter1'
See https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Grading/Grading.py#L41
and 
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/Grading/Grading.py#L29

**Comment by alphatsai** [comment]
Hi,

Thanks, it mean I have to try to figure out from the code...
How about this part 
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Grading/Grading.py#L106
Where is the definition for bed ROCs

Also, from the lines you point out, I only can understand it make grade for ROCs first from some results.
But I still can't get for full module, and how to summarize a number from "'Noise', 'VcalThresholdWidth', 'RelativeGainWidth', 'PedestalSpread', 'Parameter1'"

Thanks,
Jui-Fa

**Comment by macjohnny** [comment]
hi
the number of bad rocs is determined in https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Grading/Grading.py#L32
if there are more than 1% total problematic pixels it will consider it a BadRoc
the number of problematic pixels is calculated here:
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/Grading/Grading.py#L232
that is, pixels that are in one of the following:
DeadPixelList, MaskDefectList, DeadTrimbitsList, AddressProblemList, DeadBumpList

**Comment by macjohnny** [comment]
does this answer your question?

**Comment by alphatsai** [comment]
Hi,

So the grade in the attachment which is full module result was decided by number of bad ROCs?  
And bed ROCs was decided by the percentage of total problematic pixels?

![2015-02-13 1 45 52](https://cloud.githubusercontent.com/assets/6000932/6187475/3546188c-b387-11e4-95e1-9f7955571df3.png)

**Comment by macjohnny** [comment]
hi
the grading depends on the results of the following subtests:
'Noise', 'VcalThresholdWidth', 'RelativeGainWidth', 'PedestalSpread', 'Parameter1'
if the number of bad rocs is >1 (which is the case if there are more than 1% problematic pixels), then the grade is decreased. 
see https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Grading/Grading.py#L108
does this answer your question?

**Comment by veloxid** [comment]
@alphatsai: Is the question now answered?

**Comment by alphatsai** [comment]
Hi all,

Thanks, yes! the problem is solved 
Sorry for late reply, I was thinking how it works.

Jui-Fa
