### ISSUE TITLE
X-ray calibration does not appear in Overview.html

### ISSUE THREAD

**Issue by mcentis** [psi46/MoReWeb#50]
Hello, 
I tried to run MoReWeb with the x-ray calibration example, the program works but the test does not show up in the overview page.
Below is the output of the program.

Cheers
Matteo

MORE web analysis script, Revision number 1
GlobalFinalResultsPath: ""
AnalyseTestData ['R0215', 'VcalCalibration', '2014-07-30', '17h19m', '1406733556'] R0215_VcalCalibration_2014-07-30_17h19m_1406733556
['R0215', 'VcalCalibration', '2014-07-30', '17h19m', '1406733556'] R0215_VcalCalibration_2014-07-30_17h19m_1406733556
check wheather module R0215 with QualificationType VcalCalibration exists in DB: 
Extract Tests from config file
analyse_test_list
	-> appendXraySpectrum
	    XraySpectrumMethod with Targets ['Fe', 'Cu', 'Br', 'Mo', 'Ag', 'Sn', 'Ba']
softwareVersion: pxar
Temperature Temperature ModuleQualification_Temperature
XrayCalibrationSpectrum_1 XrayCalibration XrayCalibrationSpectrum_1
done with extraction
Working on:  {'TestDate': '1406733556', 'QualificationType': 'VcalCalibration', 'ModuleID': 'R0215'}
 -- 
    Populating Data
/space/home/localuser/MoReWeb/input/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/logfiles
analyse Temp for "/space/home/localuser/MoReWeb/input/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/logfiles/temperature.log"
Ignoring the following targets:  ['']
[(58.44, 1778.89, 1.24), (29.31, 2235.51, 0.06), (61.71, 3312.32, 0.05), (91.43, 4855.38, 0.04), (118.64, 6156.37, 0.06), (137.59, 7019.82, 0.08), (181.26, 8942.57, 0.26)] [40, 40, 40, 40, 40, 40, 40]
/space/home/localuser/MoReWeb/Analyse/TestResultClasses/CMSPixel/QualificationGroup/XrayCalibration/VcalCalibrationModule/VcalCalibrationROC/VcalCalibrationROC.py:77: UserWarning: Datapoint #1, Vcal: 29.31, Energy: 2235.51 close to Threshold
  Energy=e[1]))
['Slope', 'chi2', 'Offset']
fill row
['FluorescenceTargetModule_Ba_1_Spectrum', 'Chips_Xray', 'FluorescenceTargetModule_Cu_1_Spectrum', 'Dummy_4', 'FluorescenceTargetModule_Br_1_Spectrum', 'VcalCalibrationOffset_Spectrum', 'FluorescenceTargetModule_Mo_1_Spectrum', 'FluorescenceTargetModule_Fe_1_Spectrum', 'FluorescenceTargetModule_Ag_1_Spectrum', 'FluorescenceTargetModule_Sn_1_Spectrum', 'VcalCalibrationChi2_Spectrum', 'VcalCalibrationSlope_Spectrum', 'VcalCalibrationModule'] 'chi2'
['medianSlope', 'minSlope', 'Slopes', 'maxSlope', 'avrgSlope']
Error in subtest (write to database) TestResultClasses.CMSPixel.QualificationGroup.XrayCalibration /space/home/localuser/MoReWeb/input/R0215_VcalCalibration_2014-07-30_17h19m_1406733556/FinalResults-R001/QualificationGroup/XrayCalibrationSpectrum_1
issubclass() arg 1 must be a class
('issubclass() arg 1 must be a class',)
<type 'exceptions.TypeError'>

------

    Generating Final Output
copyfile checksum
DONE

**Comment by veloxid** [comment]
Could you please try the new HEAD of the master branch and tell me if the error is solved? There was a typo in the XrayCalibration.py

**Comment by piberger** [comment]
The problem is solved for me, I did not check it for the sample but for my own files in lion:/home/pberger/data for which I had the same problem as @mcentis before.

**Comment by veloxid** [comment]
than I mark this issue as solved

**Comment by mcentis** [comment]
Hi,
the problem is solved also for me!

Cheers
Matteo
