### ISSUE TITLE
Question for grade of module again

### ISSUE THREAD

**Issue by alphatsai** [psi46/MoReWeb#59]
Hi all,

After the answer from #47, I try to figure out which ROC is bed from MoReWeb results.
But it seems to hard to understand which bed ROC make the grade of module be B or C.
Could you use following result to point out which ROC is bed, and how to observe from this to know grade is B, please.
http://cmspixelprod.pi.infn.it/data/pixels/OUT/GLOBAL/M0297/testing-dacparams/REV001/R001/M0297_FullQualification_2015-02-11_14h41m_1423662092/QualificationGroup/ModuleFulltest_p17_1/TestResult.html 

Many thanks,
Jui-Fa

**Comment by macjohnny** [comment]
hi
sorry for the late answer.
from summary3 we have
Ped. Spread grades	15/1/0	
therefore, there are 15 rocs with grade A, and 1 with grade B, therefore the module has grade B
Check https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Grading/Grading.py#L41:L61
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/Grading/Grading.py#L29:L49
and
This is also visible in the PedestalSpread subplot, where you have one value above the limit for grade B.
can i consider this issue solved?
