### ISSUE TITLE
Issue with Path.cfg

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#60]
Question from Joaquin Siado,University of Nebraska:

Hello Felix,

My name is Joaquin Siado I am currently working at the University of Nebraska with Frank Meier. He ask me to run MORE-Web here in our Pixel Lab and gave your email address. I went through the twiki page to do so, but I ran into troubles when editing the Path.cfg file. Can you be more specific on how to edit this file? I am trying to run the code using the data on the twiki page.

If it helps this is what I get when I run the command "Python Controller.py "

MORE web analysis script, Revision number 1
Traceback (most recent call last):
  File "Controller.py", line 71, in <module>
    GlobalDataDirectory = Configuration.get('Paths', 'GlobalDataDirectory')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'Paths'

Thanks
----
Joaquin E Siado Castaneda
Graduate Student
Department of Physics and Astronomy
University of Nebraska

**Comment by veloxid** [comment]
Hi Joaquin,
Could you please provide some more information about your Paths.cfg file?
Dou you have a Paths.cfg file at all?
You need to take the default file  Paths.cfg.default, copy it and adjust it such that the Paths which are in that file exist.

**Comment by jsiado** [comment]
Hi, 
I have a file called Paths.cfg.default. I renamed Paths.cfg I changed the directories to where I have the output files. This is what I get after I run Controller.py 

 MORE web analysis script, Revision number 1
GlobalFinalResultsPath: "/home/Joaquin/M0823_FullQualification_2013-05-31_14h38m_1370003934//REV001"
Traceback (most recent call last):
  File "Controller.py", line 82, in <module>
    os.makedirs(GlobalFinalResultsPath)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 45] Operation not supported: '/home/Joaquin'

**Comment by macjohnny** [comment]
maybe you do not have the permissions to create directories in '/home/Joaquin'?
please try a subfolder.

**Comment by jsiado** [comment]
@macjohnny Thanks for your comment, I finally got it working.
