### ISSUE TITLE
Save plots in different types 

### ISSUE THREAD

**Issue by veloxid** [psi46/MoReWeb#62]
It would be great to have the option to save the canvas as different types.
There is already the option that one can set the data typ, e.g. 'svg'
but it would be great if one can say that the canvas should also be saved as annother type as well, e.g. root/png,etc
I extended already the GeneralTestResultClass by a Save Canvas method.
At the moment it is just saving it as a root file as well. Maybe we can make that nicer.
We should think about how we can make it nice...

**Comment by macjohnny** [comment]
in order to save a plot file, testresults now call self.SaveCanvas()
this will save the plot in the default file type, as well as in the additional formats specified
in SytemConfiguration.cfg: AdditionalImageFormats
should be ok?

**Comment by macjohnny** [comment]
moreover, the default behaviour can be overridden for each plot by setting e.g. 
self.ResultData['Plot']['AdditionalFormats'] = ['root'] #only save root files, no PDF

**Comment by macjohnny** [comment]
and now there is also a pdf-file link in the zoom-view of a plot (lower-right corner)

**Comment by vtavolar** [comment]
Hello,

I tried the new feature but not all plots are saved in different formats. For instance, Parameter1, PedestalSpread, RelativeGainWidth, VcalThresholdWidth in the module qualification summary page are available only in .svg. It would be nice if also these plots could be available in multiple formats.

Thanks,

Vittorio

**Comment by macjohnny** [comment]
Ciao vittorio
I fixed this. See pull request https://github.com/psi46/MoReWeb/pull/72

**Comment by vtavolar** [comment]
Ciao Esteban,
 thanks for the fast fix. I tried to run the new HEAD on some qualification data and the plots I was asking for start to appear, but unfortunately the moreweb stops with an error 

Traceback (most recent call last):
  File "Controller.py", line 335, in <module>
    AnalyseAllTestDataInDirectory(GlobalDataDirectory)
  File "Controller.py", line 265, in AnalyseAllTestDataInDirectory
    AnalyseTestData(ModuleInformationRaw,Folder)
  File "Controller.py", line 230, in AnalyseTestData
    ModuleTestResult.GenerateFinalOutput()
  File "/Users/batta/Applications/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 543, in GenerateFinalOutput
    self.ResultData['SubTestResults'][i].GenerateFinalOutput()
  File "/Users/batta/Applications/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 543, in GenerateFinalOutput
    self.ResultData['SubTestResults'][i].GenerateFinalOutput()
  File "/Users/batta/Applications/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 545, in GenerateFinalOutput
    self.GenerateDataFiles()
  File "/Users/batta/Applications/MoReWeb/Analyse/AbstractClasses/GeneralTestResult.py", line 553, in GenerateDataFiles
    self.GenerateDataFileHTML()
IOError: [Errno 2] No such file or directory: '/Users/batta/Documents/Ethz/Laboratorio/data_to_analyze//M0208_FullQualification_2015-03-24_08h30m_1427182221/FinalResults-R001/QualificationGroup/ModuleFulltestPxar_m20_1/AnalogCurrent/AnalogCurrent.svg'

I could analyse the same data without errors before updating the code.

Thanks a lot,
Vittorio

**Comment by macjohnny** [comment]
ciao vittorio
yes, you are right, there was a mistake. i corrected it an pushed it to master. please try
it again.

**Comment by macjohnny** [comment]
@vtavolar can I consider this issue done?

**Comment by vtavolar** [comment]
Sorry Esteban, I tested it but forgot to reply. It works for me, thanks.

Vittorio
