### ISSUE TITLE
scurveVthrComp_VthrComp

### ISSUE THREAD

**Issue by ursl** [psi46/MoReWeb#63]
Hi all, 

I think that the VthrComp s-curves are not used. I tried to search the moreweb code for "vthrcomp" and I only find two occurences, which I think both refer to the operational setting of this DAC. 

Can somebody please confirm that the VthrComp s-curves are not used by moreweb, indeed? If this is the case, I'll disable the measurement of these s-curves in the FullTest. This will help in speeding up the test. 

Please note that the trim algorithm runs independently of the VthrComp s-curves and will not be affected by this removal. 

Many thanks. 

Cheers,
--U.

**Comment by veloxid** [comment]
Hi Urs
As far as we are aware the VthrComp s-curve is not used and not planed to be used in the Qualification.
Cheers
Felix

**Comment by ursl** [comment]
Thanks. I removed it from the FullTest.
