### ISSUE TITLE
IV curve in central DB for FullTest and XRay

### ISSUE THREAD

**Issue by arizzi** [psi46/MoReWeb#66]
hi guys,
in order to store properly the IV measurements taken during FullTests or XRay tests we would need moreweb to have the standard hook (customWriteToDB or similar) where all needed information is available.

In particular what we need is:
- the path of the .txt file containing the IV values (e.g. M0284_FullQualification_2015-02-18_09h41m_1424248873/008_IV_p17/ivCurve.log... but we need to know the right name of the folder and file for a given test/tar.gz )
- the following information:
   *  step (see https://twiki.cern.ch/twiki/bin/view/CMS/BPixDB#File_format_for_sensor_IV_upload)
   * v1, i1, v2, i2
   *  slope
   * grade
   * temperature, date, center, comment 

is it feasible to implement this in moreweb any time soon?

@tommasoboccali

**Comment by macjohnny** [comment]
ciao @tommasoboccali 
can you explain what you mean with "would need moreweb to have the standard hook (customWriteToDB or similar) where all needed information is available."?
the slope and the currents are already available in 
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Fulltest.py#L313
so this is just to extend the information with step, grade, temperature, date, center, comment?

**Comment by arizzi** [comment]
as you can see we miss v1, v2 etc..

in addition it is not clear to us if Fulltest *always* have an IVCurve associated or not (it seems not mandatory, is it?)...

how about xray vcal? could it have an IVCurve too?

**Comment by macjohnny** [comment]
hi
fulltest does not always have an ivcurve, at least the code in https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Fulltest.py#L269 does not require an IVCurve.
what do you mean by v1, v2? voltage at 150°C?

**Comment by veloxid** [comment]
Hi
As Esteban already pointed aout, not every fulltest has an IV:
The test procedure for a full qualification is:
Fulltest@-20, Cycle, Fulltest@-20,IV@-20,Fulltest@17, IV @17

e.g. the first Fulltest does not have any IV data.

As far as I am aware xray will not contain an Iv curve.

**Comment by arizzi** [comment]
then if not all FullTest actually has an IV why should we hook the IV filling in the Fulltest.py?

how can we check if such test has the IV?
How do we know the IV directory containing the .log file?

**Comment by macjohnny** [comment]
if the variables are filled, the iv curve is present. see https://github.com/psi46/MoReWeb/blob/macjohnny-dev-ivcurve/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Fulltest.py#L266

**Comment by macjohnny** [comment]
the full path is stored, therefore you can find the directory containing the log file

**Comment by arizzi** [comment]
the full path point to a sub folder... I do not like guessing the ../ *IV*
folder... but if that is the only way we can do it
Il 05/mag/2015 17:06, "Esteban Marín" <notifications@github.com> ha scritto:

**Comment by macjohnny** [comment]
@tommasoboccali please refer to https://github.com/psi46/MoReWeb/blob/macjohnny-dev-ivcurve/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Grading/Grading.py#L106:L140 for the grading.

**Comment by macjohnny** [comment]
@arizzi yes, the path is an absolute path to the log file. as discussed with tommaso, the parsed IVdata is also available.

**Comment by tommasoboccali** [comment]
there must be a mistake: https://github.com/psi46/MoReWeb/blob/macjohnny-dev-ivcurve/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Fulltest.py#L280 says:

{'CurrentAtVoltage150V': {'Unit': '\xce\xbcA', 'Value': '0.62', 'Label': 'I(150 V)'}, 'Variation': {'Value': '1.12', 'Label': 'I(150 V) / I(100 V)'}}

so it misses the entry @ 100V, which thus reamain -1 at the end

**Comment by macjohnny** [comment]
hi
yes, you are right. check the newest commit.

**Comment by tommasoboccali** [comment]
better, but still: IVCurveData at the end is 

IVCurveData {'IVCurveFilePath': '/tmp/testiv//M2020_FullQualificationShort_2015-04-07_10h21m_1428394898/001_IV_p17/ivCurve.log', 'IVSlope': 1.1200000000000001, 'CurrentAtVoltage100V': 5.5238880102139111e-07, 'RecalculatedVoltage': 0.62, 'TestTemperature': 17.0, 'IVCurveData': {'CurrentList': array('d', [1.7486999581706186e-07, 2.7784000167230261e-07, 3.5477000892569777e-07, 4.1237001369154314e-07, 4.5999999542800651e-07, 4.8356997695009341e-07, 5.0494998049543938e-07, 5.2299998287708149e-07, 5.3897997531748842e-07, 5.5235000218090136e-07, 5.6412000049022026e-07, 5.7708001577339019e-07, 5.910999902880576e-07, 6.0551002434294787e-07, 6.2011997670197161e-07, 6.3435999209104921e-07, 6.4957998802128714e-07, 6.6695997702481691e-07, 6.8644999373645987e-07]), 'VoltageList': array('d', [9.9680004119873047, 19.979000091552734, 29.968000411987305, 39.972000122070312, 49.96099853515625, 59.951000213623047, 69.958000183105469, 79.9530029296875, 89.969001770019531, 99.967002868652344, 109.97699737548828, 119.97499847412109, 129.9739990234375, 139.98899841308594, 149.98500061035156, 159.99299621582031, 169.98399353027344, 179.9739990234375, 189.97700500488281])}, 'CurrentAtVoltage150V': 0.62}


I can make sense to CurrentAtVoltage100V (in A), but what is 
 'CurrentAtVoltage150V': 0.62 
it should be something times 10^-7
???

**Comment by tommasoboccali** [comment]
ah another thing: it seems you do not copy the ivCurle.log in the out (result) directory .... any reason not to (since now it has "value")?

**Comment by veloxid** [comment]
Hi

I agree the value should be 0.62e-6, the reason for this is that we show the value in muA, so we forgot the conversion into A. I am fixing it right now.

**Comment by arizzi** [comment]
Hi Felix,
can you confirm that such value is NOT the temperature corrected one? it
looks quite strange that it has the same value also for "recalculated".

In the DB we want to have values as measured at given temperature, the
correction to 25deg is done (optionally) later in presenting the DB results
in the webpages.

**Comment by veloxid** [comment]
Hi,
I worked on the IV Curve, it should be now correct:
Just to explain the recalculation: 
A recalculated value is given for all  fulltests with IV curve.
So if the fulltest is done at 17 deg C the recalculation gives the same value as the measured value.
If the temperature is different to the temperature recalculated to , there should be a difference to the measured value:
the calculation is done by:
I_rec =  I_real *  * T_rec^2/ T_real^2 * exp ^2 * exp(Eef / 2 / kB * (1 / T_rec - 1 / T_real))

**Comment by veloxid** [comment]
Please check and confirm if its ok.

**Comment by arizzi** [comment]
do you mean that if you measure at 16 instead of 17 degree you correct to
17 degree?
What is T_rec and T_real ?

and btw, is  CurrentAtVoltage150V corrected or not?

**Comment by veloxid** [comment]
Yes if one measured at 16 instead of 17 degC (we are talking about setpoint temperatures) the recalculated voltage is corrected to 17degC
T_Rec is the temperature one recalculates/corrects to,
T_real is the setpoint temperature at which one performed the test
CurrentAtVoltag150V is the measured value - not corrected
RecalculatedVoltage is the recalculated/correted voltage at 17degC

**Comment by arizzi** [comment]
and the temperature you give us is always 17 or would it be 16 (i.e. the
actual one)?

**Comment by macjohnny** [comment]
@arizzi @tommasoboccali what is the current status of this issue? do you need something else implemented in moreweb?

**Comment by tommasoboccali** [comment]
ciao i think we are still waiting for an answer on how the temperature is given (the real one or the recomputed one, always 17?)

**Comment by veloxid** [comment]
Just to clarify it one more time:
There is the currentAtVoltage150V that is the MEASURED value as the keithley or any other high voltage device is displaying as the current.
The recalculated voltages are extracted from the measured voltage and correspond to the current at 17degC.

If one would perform a test at 16 degC the RecalculatedCurrent I_rec is extracted from the formula above with the following values:
T_rec = 17degC = 290.15Kelvin
T_real = 16degC  = 189.15 Kelvin
I_real = measured current at 16degC

I_rec = I_real * T_rec^2/ T_real^2 * exp ^2 * exp(Eef / 2 / kB * (1 / T_rec - 1 / T_real))

Is this clear now?

**Comment by tommasoboccali** [comment]
NO
the question was another: 
then, which temperature you put in the field IVCurveData['TestTemperature'] ?
16 or 17?
If you put 16 is not ok, since you are giving us a corrected current and NOT a corrected temperature. This means we cannot recorrect later to another temperature.

you should give us a set of I1,I2 and T which is consistent (either all corrected, or not)

or even better: give us both the test and the corrected temperature

tom

**Comment by veloxid** [comment]
All currents are recaluclated to 17degC. We don't need any other recalculated value.This is for checking.
The temperature we give is the temperature where the test is performed.

With that temperature T + the measured current I_meas (that's the current which was measured at temperature T) you have everything to do a recalculateion to any other temperature...
We only need the value at 17deg to compare it  with the fulltest at 17degC

**Comment by tommasoboccali** [comment]
we don not have also i_meas.

the structure you pass us is just

        IVCurveData = {
                'CurrentAtVoltage150V':-1,
                'CurrentAtVoltage100V':-1,
                'RecalculatedVoltage':-1,
                'IVSlope':0,
                'IVCurveFilePath':'',
                'TestTemperature':'',
                'IVCurveData':{
                        'VoltageList':[],
                        'CurrentList':[]
                }
        }

**Comment by arizzi** [comment]
Hi ,
I think you did not get what tommaso said.
we need a *consistent* set, period. we do not care if it is 17 22 13 or 29.
we just need the current to be consistent with the temperature you give us.
Il 18/mag/2015 13:01, "Felix Bachmair" <notifications@github.com> ha
scritto:

**Comment by veloxid** [comment]
I think i see you issue: we will edit dthe structure that you have the following items:
    IVCurveData = {
            'CurrentAtVoltage150V':-1,
            'CurrentAtVoltage100V':-1,
            'RecalculatedCurrentAt150V’:-1,
            'RecalculatedCurrentAt100V’:-1,
            ‘recalculatedTo’:17,
            'IVSlope':0,
            'IVCurveFilePath':'',
            'TestTemperature':'',
            'IVCurveData':{
                    'VoltageList':[],
                    'CurrentList':[]
            }
    }
Is that ok?

**Comment by macjohnny** [comment]
@tommasoboccali @arizzi 
I added the values of the recalculated currents to the dict. 
can you please check if it is ok now?

**Comment by tommasoboccali** [comment]
ciao, thanks
most probably not this week :(

tom

**Comment by macjohnny** [comment]
by the way: the title of the issue states that this is also needed for the xray test. is this correct?

**Comment by tommasoboccali** [comment]
so, i am testing but I get:

IVCURVEDATA  {'RecalculatedCurrentAtVoltage150V': 6.1999999999999999e-07, 'IVCurveFilePath': '/tmp/tempJfiD/INPUT/M2020_FullQualificationShort_2015-04-07_10h21m_1428394898/001_IV_p17/ivCurve.log', 'RecalculatedToTemperature': '', 'IVSlope': 1.1200000000000001, 'CurrentAtVoltage100V': 5.5238880102139111e-07, 'IVCurveData': {'CurrentList': array('d', [1.7486999581706186e-07, 2.7784000167230261e-07, 3.5477000892569777e-07, 4.1237001369154314e-07, 4.5999999542800651e-07, 4.8356997695009341e-07, 5.0494998049543938e-07, 5.2299998287708149e-07, 5.3897997531748842e-07, 5.5235000218090136e-07, 5.6412000049022026e-07, 5.7708001577339019e-07, 5.910999902880576e-07, 6.0551002434294787e-07, 6.2011997670197161e-07, 6.3435999209104921e-07, 6.4957998802128714e-07, 6.6695997702481691e-07, 6.8644999373645987e-07]), 'VoltageList': array('d', [9.9680004119873047, 19.979000091552734, 29.968000411987305, 39.972000122070312, 49.96099853515625, 59.951000213623047, 69.958000183105469, 79.9530029296875, 89.969001770019531, 99.967002868652344, 109.97699737548828, 119.97499847412109, 129.9739990234375, 139.98899841308594, 149.98500061035156, 159.99299621582031, 169.98399353027344, 179.9739990234375, 189.97700500488281])}, 'CurrentAtVoltage150V': 6.1999999999999999e-07, 'RecalculatedCurrentAtVoltage100V': 5.5238880102139111e-07, 'TestTemperature': 17.0}

please note 

RecalculatedToTemperature': ''

so it was set to 17 in the beginnign, I cannot see who sets that back to an empty string ....
quite puzzled :(

**Comment by tommasoboccali** [comment]
it seems to happen here:

            if IVCurveTestResultData['KeyValueDictPairs'].has_key(
                    'recalculatedCurrentAtVoltage150V'):
                IVCurveData['RecalculatedCurrentAtVoltage150V'] = float(
                    IVCurveTestResultData['KeyValueDictPairs'][
                        'recalculatedCurrentAtVoltage150V']['Value'])
                IVCurveData['RecalculatedCurrentAtVoltage150V'] *= self.ResultData['SubTestResults']['IVCurve'].ResultData['KeyValueDictPairs']['recalculatedCurrentAtVoltage150V'].get('Factor',1)

            else:
                IVCurveData['RecalculatedCurrentAtVoltage150V'] = IVCurveData['CurrentAtVoltage150V']
                IVCurveData['RecalculatedToTemperature'] = IVCurveData['TestTemperature']
^^^^^^
that is where it gets an empty string

(tested printing, line before was 17, after is '')

any idea?


but why does it become a string??

**Comment by macjohnny** [comment]
ciao tommaso

you are right, the recalculated temperature was set before the test temperature. this is fixed now.

**Comment by tommasoboccali** [comment]
indentation error:
(L 307):
   
           	if IVCurveTestResultData['HiddenData'].has_key('IVCurveFilePath'):
            	IVCurveData['IVCurveFilePath'] = IVCurveTestResultData['HiddenData']['IVCurveFilePath']

I guess you meant:  

   
           if IVCurveTestResultData['HiddenData'].has_key('IVCurveFilePath'):
            	IVCurveData['IVCurveFilePath'] = IVCurveTestResultData['HiddenData']['IVCurveFilePath']


but please have a look .. the while logic seems a bit obscure to me there ;)

**Comment by macjohnny** [comment]
@tommasoboccali you are right. i fixed the indendation problem.
what do you mean with "the while logic"?

**Comment by tommasoboccali** [comment]
ciao, i think while logic is a feature of auto correction, no idea what I wanted to say ...

in any case I checked and seems fine:

http://cmspixelprod.pi.infn.it/data/pixels/t0logs/2015-05-25//27190

i need to get back to office and do the final PR on the last you sent.

in principle, all fine
