### ISSUE TITLE
Reduce number of open file descriptors

### ISSUE THREAD

**Issue by piberger** [psi46/MoReWeb#86]
Hi,

The number of open files at a time should be reduced, otherwise MoReWeb will crash if one tries to analyse a lot of data (eg. 20 qualification folders).

````
SysError in <TFile::TFile>: file /home/production/data/M2023_XRayQualification_2015-05-21_18h02m_1432224142/003_XraySpectrum_p17/commander_XraySpectrum.root can not be opened for reading (Too many open files)
````

While MoReWeb analyzes a folder, I have seen that hundreds of file descriptors from previous folders were still in use, one should somehow try to close them, being especially careful in case of handled exceptions and errors.

A workaround is to limit the amount of new qualification folders analyzed at once or running "ulimit -n 2048".

**Comment by macjohnny** [comment]
compare with 
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/BareModuleTest/Chips/Chip/Chip.py#L125
if the file handles are set in self.FileHandle, then they can be closed as soon as the parent object is done.
@piberger can you implement this?

**Comment by piberger** [comment]
Yes, I can implement this, but I would consider other task to have more priority at the moment and I'm going to Pixel Workshop on sunday, it would therefore take a while then.
