### ISSUE TITLE
Question regarding mask defect and address decoding tests

### ISSUE THREAD

**Issue by ursl** [psi46/MoReWeb#87]
Hi all, 

at the moment pXar displays the mask defect (MaskTest_C\*_V0) and address decoding (AddressDecodingTest_C\*_V0) TH2D's with a binary logic: working pixels have bin content 1, faulty pixels have bin content 0. This also includes dead pixels. This need not be the case, as faulty pixels could be set to negative values (this used to be the case previously). In fact now again we'd like to move back to tri-state displays (1 for working, -1 for faulty, and 0 for dead pixels). 

I tried to understand in MoReWeb whether that would induce problems or require changes. I am not quite sure about my findings. 

I think that the mask defects are handled in 

https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/PixelMap/PixelMap.py#L116

If correct I would think that the current pxar histograms would never lead to a mask defect as negative bin contents are reset to zero (in pXar). So moving back to tri-state logic here would cure a problem (maybe). 

The address decoding seems to be handled in 

https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/AddressDecoding/AddressDecoding.py#L42

This would not be affected by setting address decoding errors to -1 and dead pixels to 0. 

So my conclusion is that going (back) to tri-state logic for these TH2D's does not induce changes in MoReWeb (rather it solves possibly a problem in the mask defect analysis). 

Would you agree?

Many thanks. 

Cheers,
--U.

**Comment by macjohnny** [comment]
hi
you are right about the mask defects, but since dead pixels are evaluated in
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/PixelMap/PixelMap.py#L99
this would need a small change.

**Comment by ursl** [comment]
Hi Esteban, 

I am not sure I understand. Dead pixels would stay at 0 in all maps (PixelAlive, MaskTest, AddressDecodingTest). Is that not OK with 

https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/PixelMap/PixelMap.py#L99

?

Cheers,
--U.

**Comment by macjohnny** [comment]
ah, ok, i thought negative values would also be allowed for dead pixels.
but if this is not the case, then there should be no changes to moreweb.

**Comment by piberger** [comment]
at the moment the analysis is not working correctly, I will fix this problem soon

eg.
https://github.com/psi46/MoReWeb/blob/master/Analyse/TestResultClasses/CMSPixel/QualificationGroup/Fulltest/Chips/Chip/AddressDecoding/AddressDecoding.py#L42

**Comment by piberger** [comment]
should be fixed now
