### ISSUE TITLE
Question on IV-test data

### ISSUE THREAD

**Issue by thweiler** [psi46/MoReWeb#91]
Hi
When I run the IV-test in pxar, it fails to be analysed, with following message:
{'ErrorCode': Exception('Cannot find column "current" in IV tuple: [\'Iv Test From Wed, 17 Jun 2015 17:20:28 +0200  +769130000 Nsec\']',), 'FinalResultsStoragePath': '/Users/weiler/psiexpert/MoReWeb/DATA/FinalResults/REV001/R001/M4550_Fulltest_2015-06-17_12h52m03s_1434538323/QualificationGroup/ModuleFulltest_p17_1/IVCurve', 'ModulePath': 'TestResultClasses.CMSPixel.QualificationGroup.Fulltest.IVCurve'} 

Changing the iv-curve.log format from:
#_IV test from Wed, 17 Jun 2015 17:20:28 +0200 (CEST) +769130000 nsec
#Test Parameters:
#__HV Supply:      Keithley2410
#__Voltage Start:  0
#__Voltage Stop:   600
#__Voltage Step:   5
#__Delay(s):       1
#__Compliance(uA): 100
#voltage(V)     current(A)      timestamp
  +0.000        -7.185225e-08   2015-06-17 15:20:28.769130000Z
  -5.000        -3.630060e-07   2015-06-17 15:20:30.460919000Z
(the "_" is indicating a blank )

to following format:
#---LOG IV test from Wed, 17 Jun 2015 17:20:28 +0200 (CEST) +769130000 nse --- 
#---LOGTest Parameters --- 
#---LOG   HV Supply:      Keithley241 --- 
#---LOG   Voltage Start:   --- 
#---LOG   Voltage Stop:   60 --- 
#---LOG   Voltage Step:    --- 
#---LOG   Delay(s):        --- 
#---LOG   Compliance(uA): 10 --- 
#voltage(V)     current(A)      timestamp
  +0.000        -7.185225e-08   769130000
  -5.000        -3.630060e-07   460919000
it works.
Is there an easy way to adapt the expected format in a configuration file? 
Am I the only one having this problem? 

cheers
Thomas

**Comment by piberger** [comment]
Hi Thomas,

the way this file is analyzed, is hard-coded at the moment. The information on which column contains which quantity is taken from the first line, which:
- is not equal to "#"
- does not contain the sequence "LOG"
- is not empty

which is 

    #IV test from Wed, 17 Jun 2015 17:20:28 +0200 (CEST) +769130000 nsec

in your first example, which does not contain the information.

How do you log the iv data? Why not just adding the "LOG" to all lines in the header in the data logger?

cheers,
Pirmin

**Comment by thweiler** [comment]
Hi Pirmin
I am using pXar, just starting the iv test from the gui.  
OK I can ask Urs to change in pXar, but I was curious if there was 
another solution or I am the only one having this problem.
Is MoReWeb able to handle the pXar time stamps?
+0.000 -7.185225e-08 2015-06-17 15:20:28.769130000

cheers
Thomas

**Comment by piberger** [comment]
Hi Thomas,

we are not using pXar for the IV and therefore did not notice this problem.
pxar is the official software so we will change MoReWeb to be compatible with the pxar log file format.

cheers,
Pirmin

**Comment by piberger** [comment]
can you please send me one of your ivcurve files?

**Comment by piberger** [comment]
Hi Thomas,
please try the IVCurveFormat branch.
Timestamps are not used for the IV curves, therefore we don't need to read it.

**Comment by thweiler** [comment]
Hello Pirmin
The IVCurveFormat branch works for pXar iv-test output.
Thanks for the changes.
Cheers
Thomas

**Comment by piberger** [comment]
Hi Thomas, 
thanks for confirmation, I will merge it into master.
